#!/usr/bin/env bash
# Headless build of the CubeMX-generated BallDetector_N6 CubeIDE project — no
# GUI window opens. Produces Debug/BallDetector_N6.{elf,bin}.
#
# Prereq: the project has been generated by CubeMX in-place (this directory
# holds the .project/.cproject + Core/, Drivers/, Middlewares/, X-CUBE-AI/).
# Run scripts/stedgeai_compile.sh first if model/ changed.

set -euo pipefail

# --- adjust me ----------------------------------------------------------------
CUBEIDE_HEADLESS="${CUBEIDE_HEADLESS:-/opt/st/stm32cubeide_2.1.1/headless-build.sh}"
WORKSPACE="${WORKSPACE:-/tmp/cubeide_ws_balldetector_n6}"
ECLIPSE_CONFIG="${ECLIPSE_CONFIG:-/tmp/cubeide_cfg_balldetector_n6}"
CONFIG="${CONFIG:-Debug}"
# ------------------------------------------------------------------------------

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="$(cd "$HERE/.." && pwd)"
# The N6 CubeMX project is multi-context: the buildable Eclipse project is the
# FSBL sub-project (the app), named "BallDetector_N6_FSBL".
FSBL="$PROJ/FSBL"
PROJ_NAME="${PROJ_NAME:-BallDetector_N6_FSBL}"

if [[ ! -f "$FSBL/.cproject" ]]; then
  echo "no CubeIDE FSBL project ($FSBL/.cproject missing)." >&2
  echo "generate it first with CubeMX (Board Selector -> NUCLEO-N657X0-Q," >&2
  echo "X-CUBE-AI + DCMIPP/IMX335 + USART1@VCP), output in-place. See README." >&2
  exit 1
fi
if [[ ! -x "$CUBEIDE_HEADLESS" ]]; then
  echo "CubeIDE headless builder not found: $CUBEIDE_HEADLESS" >&2; exit 1
fi
if ! ls "$FSBL"/X-CUBE-AI/App/network*.c >/dev/null 2>&1; then
  echo "FSBL/X-CUBE-AI/App/network*.c missing — generate via CubeMX or scripts/stedgeai_compile.sh." >&2
  exit 1
fi

echo "==> headless build  ($PROJ_NAME/$CONFIG, workspace: $WORKSPACE)"
# Fresh workspace + output dir each time so .project/.cproject changes are
# fully re-imported and the makefiles (sources.mk/subdir.mk) regenerate.
rm -rf "$WORKSPACE" "$ECLIPSE_CONFIG" "$FSBL/$CONFIG"
# NOTE: the CubeIDE headless builder exits non-zero and prints a phantom
# "N errors" from the CDT indexer even on a clean gcc build, so we DON'T trust
# its exit code — we gate success on the .elf/.bin actually being produced.
ELF="$FSBL/$CONFIG/$PROJ_NAME.elf"
BIN="$FSBL/$CONFIG/$PROJ_NAME.bin"
rm -f "$ELF" "$BIN"
"$CUBEIDE_HEADLESS" \
  -data "$WORKSPACE" \
  -configuration "$ECLIPSE_CONFIG" \
  -import "$FSBL" \
  -cleanBuild "$PROJ_NAME/$CONFIG" || true

echo
if [[ -f "$ELF" && -f "$BIN" ]]; then
  echo "==> build OK — artifacts:"
  ls -lh "$ELF" "$BIN" | sed 's/^/  /'
else
  echo "==> build FAILED — no .elf/.bin produced; inspect the log above." >&2
  exit 1
fi
