#!/usr/bin/env bash
# Headless build of the CubeMX-generated BallDetector_N6 CubeIDE project — no
# GUI window opens. Produces Debug/BallDetector_N6.{elf,bin}.
#
# Prereq: the project has been generated by CubeMX in-place (this directory
# holds the .project/.cproject + Core/, Drivers/, Middlewares/, X-CUBE-AI/).
# Run scripts/stedgeai_compile.sh first if model/ changed.

set -euo pipefail

# --- adjust me ----------------------------------------------------------------
CUBEIDE_HEADLESS="${CUBEIDE_HEADLESS:-/opt/st/stm32cubeide_2.1.1/headless-build.sh}"
WORKSPACE="${WORKSPACE:-/tmp/cubeide_ws_balldetector_n6}"
CONFIG="${CONFIG:-Debug}"
# ------------------------------------------------------------------------------

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="$(cd "$HERE/.." && pwd)"

if [[ ! -f "$PROJ/.cproject" ]]; then
  echo "no CubeIDE project here ($PROJ/.cproject missing)." >&2
  echo "generate it first with CubeMX (Board Selector -> NUCLEO-N657X0-Q," >&2
  echo "X-CUBE-AI + DCMIPP/IMX335 + UART), output in-place. See README." >&2
  exit 1
fi
if [[ ! -x "$CUBEIDE_HEADLESS" ]]; then
  echo "CubeIDE headless builder not found: $CUBEIDE_HEADLESS" >&2; exit 1
fi
if [[ ! -d "$PROJ/X-CUBE-AI/App" || ! -f "$PROJ/X-CUBE-AI/App/network.c" ]]; then
  echo "X-CUBE-AI/App/network.c missing — run scripts/stedgeai_compile.sh first." >&2
  exit 1
fi

echo "==> headless build  (config: $CONFIG, workspace: $WORKSPACE)"
# -import (re)registers the project in a throwaway workspace, then -build it.
"$CUBEIDE_HEADLESS" \
  -data "$WORKSPACE" \
  -import "$PROJ" \
  -cleanBuild "BallDetector_N6/$CONFIG"

echo
echo "==> artifacts:"
ls -lh "$PROJ/$CONFIG/"BallDetector_N6.{elf,bin} 2>/dev/null | sed 's/^/  /' || {
  echo "  (no .elf/.bin in $CONFIG/ — check the build log above)" >&2; exit 1; }
